### Get all categories
GET http://localhost:3000/categories
content-type: application/json

### Get category by id
GET http://localhost:3000/categories/23
content-type: application/json

### Create category
POST http://localhost:3000/categories
content-type: application/json

{
    "title": "message"
}

### Update category
PUT http://localhost:3000/categories/25
content-type: application/json

{
    "title": "Category updated"
}

###delete category
DELETE http://localhost:3000/categories/24
content-type: application/json