### Get all notes
GET http://localhost:3000/notes
content-type: application/json

### Get note by id
GET http://localhost:3000/notes/26
content-type: application/json

### Create note
POST http://localhost:3000/notes
content-type: application/json

{
    "title": "noldea"

}

### Update note
PUT http://localhost:3000/notes/25
content-type: application/json

{
    "title": "notes updated",
    "description": "adwadwadwads"

}

### Delete note
DELETE http://localhost:3000/notes/25
content-type: application/json