### Get all notes
GET http://localhost:3000/notes
content-type: application/json

### Get note by id
GET http://localhost:3000/notes/15
content-type: application/json

### Create note
POST http://localhost:3000/notes
content-type: application/json

{
    "title": "dwadwa dwadwadwada"
}

### Update note
PUT http://localhost:3000/notes/15
content-type: application/json

{
    "title": "Nota editada con refactoring",    
}

### Delete note
DELETE http://localhost:3000/notes/42
content-type: application/json